**251100610017 - SRIRAM K**

In [ ]:
yy = 440 *12
print(yy)

zz = 2500 / 1000
print(zz)

xx = 2500 % 1000
print(xx)

print(10/2)
print(10//2)

print(9/2)
print(9//2)



big = max('Hello world')
print(big)

tiny = min('helloworld')
print(tiny)



5280
2.5
500
5.0
5
4.5
4
w
d


In [ ]:
list = [89 , 14 , 21 , 34 , 55 , 3]
biggest = max(list)
print(biggest)

smallest = min(list)
print(smallest)

89
3


In [ ]:
list = [89 , 14 , 21, 34 , 55 , 3]
ans = []
for num in list:
  if(num > 50):
      ans.append(num)
print(ans)


x = int(input("Enter a hours: "))
y = int(input("Enter a pay rate: "))

pay = x * (float(y))
print(pay)

[89, 55]
Enter a hours: 35
Enter a pay rate: 9
315.0


Count number of elements in the list.

In [ ]:
list = [89 , 14 , 21, 34 , 55 , 3]
length = 0
for num in list:
  length += 1
print(length)

6


Find the sum and average in the list


In [ ]:
list = [89 , 14 , 21, 34 , 55 , 3]
sum = 0
avg = 0
for num in list:
  sum += num

print(sum)
avg = sum / len(list)
print(avg)

216
36.0


In [ ]:
def computePay(hours, pay_rate):
  if hours <= 40:
    total_pay = hours * pay_rate
  else:
    regular_pay = 40 * pay_rate
    overtime_hours = hours - 40
    overtime_pay = overtime_hours * (pay_rate * 1.5)
    total_pay = regular_pay + overtime_pay
  return total_pay


try:
  hours_worked = float(input("Enter hours: "))
  pay_rate = float(input("Enter pay rate: "))

  total_pay = computePay(hours_worked, pay_rate)
  print(f"Total pay: {total_pay}")

except ValueError:
  print("Invalid input. Please enter numerical values for hours and pay rate.")

Enter hours: 40
Enter pay rate: nine
Invalid input. Please enter numerical values for hours and pay rate.


In [ ]:
def bubble_sort(arr):
    n = len(arr)

    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr

arr = [89 , 14 , 21, 34 , 55 , 3]
sorted_arr = bubble_sort(arr)
print("Sorted array:", sorted_arr)


Sorted array: [3, 14, 21, 34, 55, 89]


Insertion sort in arrays

In [ ]:
def insertion_sort(arr):
    n = len(arr)
    for i in range(1, n):
        key = arr[i]

        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

list = [89 , 14 , 21, 34 , 55 , 3]
insertion_sort(list)
print("Sorted array is:",list)

Sorted array is: [3, 14, 21, 34, 55, 89]


Quick sort in list


In [ ]:
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[len(arr) // 2]
        less = [x for x in arr if x < pivot]
        equal = [x for x in arr if x == pivot]
        greater = [x for x in arr if x > pivot]
        return quick_sort(less) + equal + quick_sort(greater)


list = [89 , 14 , 21, 34 , 55 , 3]
sorted_data = quick_sort(list)
print("Sorted Array:", sorted_data)

Sorted Array: [3, 14, 21, 34, 55, 89]


write the output of the following code:


In [ ]:
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12)
print(hw12)

hello
5
hello world
hello world 12


In [ ]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))
print('  world '.strip())

In [ ]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))
print('  world '.strip())

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


rewrite the following code using list comprehension technique.

nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)  

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)


[0, 1, 4, 9, 16]


4. Consider the following dictionary

d = {'person': 2, 'cat': 4, 'spider': 8}

write a code to iterate over the keys to print "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for animal, legs in d.items():
    print(f"A {animal} has {legs} legs")

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


5. use the items method to rewrite the above code to access the keys and their corresponding values.

In [ ]:
d = {'person': 2, 'cat': 4, 'spider': 8}

for animal, legs in d.items():
    print(f"A {animal} has {legs} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


6. Write the output of the following lines

In [ ]:
nums = list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8, 9]
print(nums)

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


7. Write the differences between the following two code block

	animals = ['cat', 'dog', 'monkey']
	for animal in animals:
    	    print(animal)


	animals = ['cat', 'dog', 'monkey']
	for idx, animal in enumerate(animals):
    	    print('#%d: %s' % (idx + 1, animal))

code block 1: Iterates over the list and prints each animal.

In [ ]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


code block 2 :  Iterates over the list and prints each animal with its position (starting from 1).

In [ ]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


8. Consider the following code

	nums = [0, 1, 2, 3, 4]
	squares = []
	for x in nums:
    	    squares.append(x ** 2)
	print(squares)

    rewrite the above code using a list comprehension technique

In [ ]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)


[0, 1, 4, 9, 16]


9. Rewrite the above code to print the square of the even numbers given in the list.

	nums = [0, 1, 2, 3, 4]

In [ ]:
nums = [0,1,2,3,4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)


[0, 4, 16]


10. Write a program using dictionaries to prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

In [ ]:
legs = {
    'person': 2,
    'cat': 4,
    'spider': 8
}
for animal, count in legs.items():
    print(f"A {animal} has {count} legs")


A person has 2 legs
A cat has 4 legs
A spider has 8 legs


11. Rewrite the above program (10) using the items method to access to keys and their corresponding values.

In [ ]:
legs = {
    'person': 2,
    'cat': 4,
    'spider': 8
}
for animal, count in legs.items():
    print(f"A {animal} has {count} legs")

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


12. Write the output of the following code

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


13. Write the output of the following code

In [ ]:
import numpy as np

a = np.zeros((2,2))
print(a)


b = np.ones((1,2))
print(b)

c = np.full((2,2), 7)
print(c)


d = np.eye(2)
print(d)


e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.99797435 0.85323567]
 [0.26643176 0.58703482]]


15. Create the following rank 2 array with shape (3, 4)
	 [[ 1  2  3  4]
	  [ 5  6  7  8]
	  [ 9 10 11 12]]

	 Use slicing to pull out the subarray consisting of the first 2 rows
	 and columns 1 and 2; b is the following array of shape (2, 2):
	 [[2 3]
	  [6 7]]

In [ ]:
import numpy as np


a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])


b = a[:2, 1:3]

print("Original array:\n", a)
print("Sliced subarray:\n", b)

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced subarray:
 [[2 3]
 [6 7]]


15. Consider the following

	a1 = np.array([[1,2], [3, 4], [5, 6]])

    Find the elements of a1 that are bigger than 2;  
    Write your comments on the type and shape of the resultant array.

In [ ]:
import numpy as np
a1 = np.array([[1, 2], [3, 4], [5, 6]])

result = a1[a1 > 2]

print(result)


[3 4 5 6]


16. Write your comments on the output of the following code

In [ ]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))
print(np.dot(v, w))

print(x.dot(v))
print(np.dot(x, v))

print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


17. Let x = np.array([[1,2],[3,4]])
    Write the code to perform the following
	(a) Compute sum of all elements of x.
	(b) Compute sum of each column of x.
	(c) Compute sum of each row of x.


In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 4]])


total_sum = np.sum(x)

column_sum = np.sum(x, axis=0)

row_sum = np.sum(x, axis=1)

print("Sum of all elements:", total_sum)
print("Sum of each column:", column_sum)
print("Sum of each row:", row_sum)

Sum of all elements: 10
Sum of each column: [4 6]
Sum of each row: [3 7]


**251100610017 - SRIRAM K**