**251100610017-SRIRAM K**

1) Data preprocessing steps
2) importing the libraries
3) importing the dataset
4) taking care of missing data
5) encoding catagorical data
6) encoding categorical data
7) train test split
8) feature scaling

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data.csv')
dataset=data
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

from matplotlib import pyplot as plt
data['Age'].plot(kind='hist', bins=20, title='Age')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Salary'].plot(kind='hist', bins=20, title='Salary')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Country').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Purchased').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Age', y='Salary', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Age'].plot(kind='line', figsize=(8, 4), title='Age')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Salary'].plot(kind='line', figsize=(8, 4), title='Salary')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Purchased'].value_counts()
    for x_label, grp in data.groupby('Country')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Country')
_ = plt.ylabel('Purchased')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Country'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Age', y='Country', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Purchased'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Age', y='Purchased', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Country'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Salary', y='Country', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Purchased'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Salary', y='Purchased', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
#independent variables
#dataset
X = dataset.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#split dependent variables
y=dataset.iloc[: ,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#Encoding catagorical data
#Encoding the independent variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("Country", OneHotEncoder(), [0])], remainder = 'passthrough')
X = ct.fit_transform(X)
X.astype(int)

array([[    1,     0,     1,     0,     1,     0,     0,    44, 72000],
       [    0,     1,     0,     1,     0,     0,     1,    27, 48000],
       [    0,     1,     0,     1,     0,     1,     0,    30, 54000],
       [    0,     1,     0,     1,     0,     0,     1,    38, 61000],
       [    0,     1,     0,     1,     0,     1,     0,    40, 63777],
       [    1,     0,     1,     0,     1,     0,     0,    35, 58000],
       [    0,     1,     0,     1,     0,     0,     1,    38, 52000],
       [    1,     0,     1,     0,     1,     0,     0,    48, 79000],
       [    0,     1,     0,     1,     0,     1,     0,    50, 83000],
       [    1,     0,     1,     0,     1,     0,     0,    37, 67000]])

In [ ]:
labelencode_y=LabelEncoder()
y=labelencode_y.fit_transform(y)
y


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_test.astype(int)
#X_test

array([[    0,     1,     0,     1,     0,     1,     0,    30, 54000],
       [    0,     1,     0,     1,     0,     1,     0,    50, 83000]])

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
X_test


array([[-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         2.64575131, -0.77459667,  1.98496442,  2.13981082]])

In [ ]:
X_train

array([[-1.        ,  1.        , -1.        ,  1.        , -1.        ,
         2.64575131, -0.77459667,  0.26306757,  0.12381479],
       [ 1.        , -1.        ,  1.        , -1.        ,  1.        ,
        -0.37796447, -0.77459667, -0.25350148,  0.46175632],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
        -0.37796447,  1.29099445, -1.97539832, -1.53093341],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
        -0.37796447,  1.29099445,  0.05261351, -1.11141978],
       [ 1.        , -1.        ,  1.        , -1.        ,  1.        ,
        -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ,
        -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
       [ 1.        , -1.        ,  1.        , -1.        ,  1.        ,
        -0.37796447, -0.77459667,  0.95182631,  0.98614835],
       [ 1.        , -1.        ,  1.        , -1.        ,  1

Dataset2:bestsellars.csv


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
data=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/bestsellers.csv')
dataset=data
dataset

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7  17350.0    8.0  2016  Non Fiction  
1                Stephen King          4.6   2052.0   22.0  2011      Fiction  
2          Jordan B. Peterson          4.7  18979.0   15.0  2018  Non Fiction  
3               George Orwell          4.7  21424.0    6.0  2017      Fiction  
4    National Geographic Kids          4.8   7665.0   12.0  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9   9413.0    8.0  2019      Fiction  
546               Jen Sincero          4.7  14331.0    8.0  2016  Non Fiction  
547               Jen Sincero          4.7  14331.0    8.0  2017  Non Fiction  
548               Jen Sincero          4.7  14331.0    8.0  2018  Non Fiction  
549               Jen Sincero          4.7  14331.0    8.0  2019  Non Fiction  

[550 rows x 7 columns]

from matplotlib import pyplot as plt
data['User Rating'].plot(kind='hist', bins=20, title='User Rating')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Reviews'].plot(kind='hist', bins=20, title='Reviews')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Price'].plot(kind='hist', bins=20, title='Price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data['Year'].plot(kind='hist', bins=20, title='Year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
data.groupby('Genre').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='User Rating', y='Reviews', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Reviews', y='Price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
data.plot(kind='scatter', x='Price', y='Year', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Year']
  ys = series['User Rating']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Genre')):
  _plot_series(series, series_name, i)
  fig.legend(title='Genre', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('User Rating')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Year']
  ys = series['Reviews']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Genre')):
  _plot_series(series, series_name, i)
  fig.legend(title='Genre', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('Reviews')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['Year']
  ys = series['Price']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Genre')):
  _plot_series(series, series_name, i)
  fig.legend(title='Genre', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('Price')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Year']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Year'}, axis=1)
              .sort_values('Year', ascending=True))
  xs = counted['Year']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('Year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Genre')):
  _plot_series(series, series_name, i)
  fig.legend(title='Genre', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Year')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
data['User Rating'].plot(kind='line', figsize=(8, 4), title='User Rating')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Reviews'].plot(kind='line', figsize=(8, 4), title='Reviews')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
data['Year'].plot(kind='line', figsize=(8, 4), title='Year')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Genre'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='User Rating', y='Genre', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Genre'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Reviews', y='Genre', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Genre'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Price', y='Genre', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(data['Genre'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(data, x='Year', y='Genre', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [ ]:
# independent variables
# dataset
J = dataset.iloc[:, [0, 1, 2, 3, 4, 5, 6]].values
J

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, ..., 8.0, 2016,
        'Non Fiction'],
       ['11/22/63: A Novel', 'Stephen King', 4.6, ..., 22.0, 2011,
        'Fiction'],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, ..., 15.0, 2018, 'Non Fiction'],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, ..., 8.0, 2017, 'Non Fiction'],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, ..., 8.0, 2018, 'Non Fiction'],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, ..., 8.0, 2019, 'Non Fiction']], dtype=object)

In [ ]:
Y= dataset.iloc[: ,6].values
Y

array(['Non Fiction', 'Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Fiction', 'Non Fiction',
       'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction', 'Fiction',
       'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Non Fiction', 'Non Fiction', 'Fiction', 'Non Fiction',
       'Non Fiction', 'Fiction', 'Fiction', 'Non Fiction', 'Non Fiction',
       'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction', 'Fiction',
       'Fiction', 'Non F

In [ ]:
missing_values=dataset.isnull().sum()
missing_values

Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer = imputer.fit(J[:,1:6])
J[:,1:6]=imputer.transform(J[:,1:6])
J

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019]], dtype=object)

In [ ]:
# Removed LabelEncoder for J as OneHotEncoder is used.
# from sklearn.preprocessing import LabelEncoder
# labelencoder_J = LabelEncoder()
# J[ :0,-2] = labelencoder_J.fit_transform(J[ :0,-2])
# print(J)

[[0 'JJ Smith' 4.7 17350.0 8.0 2016]
 [1 'Stephen King' 4.6 2052.0 22.0 2011]
 [2 'Jordan B. Peterson' 4.7 18979.0 15.0 2018]
 ...
 [350 'Jen Sincero' 4.7 14331.0 8.0 2017]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2018]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2019]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Applying OneHotEncoder to 'Name', 'Author', and 'Genre' columns
# Assuming 'Name' is at index 0, 'Author' is at index 1, and 'Genre' is at index 6 in your J array
ct = ColumnTransformer(transformers=[('name_encoder', OneHotEncoder(), [0]),
                                     ('author_encoder', OneHotEncoder(), [1]),
                                     ('genre_encoder', OneHotEncoder(), [6])],
                       remainder='passthrough')

J = ct.fit_transform(J)

# You might want to convert J to a pandas DataFrame for better readability and handling of column names
# For now, keeping it as a numpy array as in the original code
# print(J.astype(int)) # This might result in a large array of integers, consider displaying a part of it or converting to DataFrame
print(J)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3838 stored elements and shape (550, 605)>
  Coords	Values
  (0, 0)	1.0
  (0, 465)	1.0
  (0, 600)	1.0
  (0, 601)	4.7
  (0, 602)	17350.0
  (0, 603)	8.0
  (0, 604)	2016.0
  (1, 1)	1.0
  (1, 570)	1.0
  (1, 599)	1.0
  (1, 601)	4.6
  (1, 602)	2052.0
  (1, 603)	22.0
  (1, 604)	2011.0
  (2, 2)	1.0
  (2, 485)	1.0
  (2, 600)	1.0
  (2, 601)	4.7
  (2, 602)	18979.0
  (2, 603)	15.0
  (2, 604)	2018.0
  (3, 3)	1.0
  (3, 446)	1.0
  (3, 599)	1.0
  (3, 601)	4.7
  :	:
  (546, 601)	4.7
  (546, 602)	14331.0
  (546, 603)	8.0
  (546, 604)	2016.0
  (547, 350)	1.0
  (547, 472)	1.0
  (547, 600)	1.0
  (547, 601)	4.7
  (547, 602)	14331.0
  (547, 603)	8.0
  (547, 604)	2017.0
  (548, 350)	1.0
  (548, 472)	1.0
  (548, 600)	1.0
  (548, 601)	4.7
  (548, 602)	14331.0
  (548, 603)	8.0
  (548, 604)	2018.0
  (549, 350)	1.0
  (549, 472)	1.0
  (549, 600)	1.0
  (549, 601)	4.7
  (549, 602)	14331.0
  (549, 603)	8.0
  (549, 604)	2019.0


**251100610017-SRIRAM K**